name: Test Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SHELL: /bin/bash  # Explicitly set SHELL environment variable
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run test workflow
        run: |
          # Create test workflow file
          cat > test-workflow.yml <<EOF
          name: Test
          on: [push]
          jobs:
            test:
              runs-on: ubuntu-latest
              steps:
                - run: echo "Hello from test workflow"
                - run: date
                - run: pwd
          EOF
          
          # Run with explicit SHELL setting
          nix run github:samrose/beam-action -- test-workflow.yml 