name: Test Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SHELL: /bin/bash
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main

      - name: Test Package
        run: |
          nix develop -c sh -c "cd beam_action && mix test"

      - name: Cleanup
        if: always()
        run: |
          /nix/nix-installer uninstall --no-confirm
